apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        - name: SA_PASSWORD
          value: "yourWeak(!)Password"
        ports:
        - containerPort: 1433
          name: sqlserver
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  ports:
  - port: 1433
  selector:
    app: sqlserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-silo
  labels:
    app: chaos-silo
spec:
  selector:
    matchLabels:
      app: chaos-silo
  replicas: 1
  template:
    metadata:
      labels:
        app: chaos-silo
    spec:
      containers:
      - name: main
        image: orlaks.azurecr.io/chaos-silo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 11111
        - containerPort: 30000
        - containerPort: 8888
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 4Gi
        env:
        # Configure OTLP
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://aspire-dashboard:18889
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # dotnet-monitor
        - name: DOTNET_DiagnosticPorts
          value: /diag/dotnet-monitor.sock
        - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
          value: "120"
        volumeMounts:
        - mountPath: /diag
          name: diagvol
      - name: monitor
        image: mcr.microsoft.com/dotnet/monitor:8
        # DO NOT use the --no-auth argument for deployments in production; this argument is used for demonstration
        # purposes only in this example. Please continue reading after this example for further details.
        args: [ "collect", "--no-auth" ]
        imagePullPolicy: Always
        env:
        - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
          value: Listen
        - name: DOTNETMONITOR_Storage__DefaultSharedPath
          value: /diag
        # ALWAYS use the HTTPS form of the URL for deployments in production; the removal of HTTPS is done for
        # demonstration purposes only in this example. Please continue reading after this example for further details.
        - name: DOTNETMONITOR_Urls
          value: http://localhost:52323
        # The metrics URL is set in the CMD instruction of the image by default. However, this deployment overrides that with the args setting; manually set the URL to the same value using configuration.
        - name: DOTNETMONITOR_Metrics__Endpoints
          value: http://+:52325
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
      terminationGracePeriodSeconds: 180
      volumes:
      - name: diagvol
        emptyDir: {}
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 10
      maxSurge: 10

---
# In order to be able to access the service from outside the cluster, we will need to add a Service object
apiVersion: v1
kind: Service
metadata:
  name: chaos-silo
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: orleans-dashboard
    port: 8888
    targetPort: 8888
  selector:
    app: chaos-silo

---
apiVersion: v1
kind: Service
metadata:
  name: aspire-dashboard
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 18888
    targetPort: 18888
  - name: otlp
    port: 18889
    targetPort: 18889
  selector:
    app: aspire-dashboard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspire-dashboard
  labels:
    app: aspire-dashboard
spec:
  selector:
    matchLabels:
      app: aspire-dashboard
  replicas: 1
  template:
    metadata:
      labels:
        app: aspire-dashboard
    spec:
      containers:
        - name: main
          image: mcr.microsoft.com/dotnet/aspire-dashboard:8.2
          imagePullPolicy: Always
          ports:
          - containerPort: 18888
          - containerPort: 18889
          env:
            - name: DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS
              value: "true"
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 8Gi
      terminationGracePeriodSeconds: 180
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

# For RBAC-enabled clusters, the Kubernetes service account for the pods may also need to be granted the required access:
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [ "" ]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ''
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ''
