<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningLevel>3</WarningLevel>
    <AnalysisLevel>preview</AnalysisLevel>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <IsOrleansFrameworkPart>false</IsOrleansFrameworkPart>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Orleans.DurableTasks.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orleans.Serialization\Orleans.Serialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.IO" />
    <Using Include="System.Linq" />
    <Using Include="System.Net.Http" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>

</Project>
