trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - samples

pr: none

schedules:
- cron: "0 0 * * *"
  displayName: '[3.x] Daily midnight build (including CodeQL)'
  branches:
    include:
    - 3.x
  always: true

variables:
- template: vars.yaml

jobs:
- template: build.yaml