<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Orleans.Legacy.CodeGenerator</AssemblyName>
    <RootNamespace>Orleans.Legacy.CodeGenerator</RootNamespace>
    <PackageId>Microsoft.Orleans.Legacy.CodeGenerator</PackageId>
    <TargetFrameworks>$(StandardTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageReference Include="System.Runtime" Version="$(SystemRuntimeVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsLoggingVersion)" />
  </ItemGroup>
</Project>