<Project>
  <!-- Begin Orleans: Without these lines the project won't build properly -->
  <!-- Set path to code generator -->
  <PropertyGroup>
    <OrleansGenerateCodeDependsOn>$(OrleansGenerateCodeDependsOn)</OrleansGenerateCodeDependsOn>
  </PropertyGroup>

  <PropertyGroup>
    <DotNetHost Condition="'$(DotNetHost)' == ''">dotnet</DotNetHost>
    <Asm>Orleans.CodeGenerator.MSBuild.Bootstrap</Asm>
    <OrleansCodeGenCoreAssembly>$(MSBuildThisFileDirectory)src/BootstrapBuild/publish/$(Asm).dll</OrleansCodeGenCoreAssembly>
  </PropertyGroup>
  
  <Import Condition=" '$(OrleansBuildTimeCodeGen)' == 'true' " Project="$(MSBuildThisFileDirectory)src/Orleans.CodeGenerator.MSBuild/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets" />
  <!--End Orleans -->

  <!-- Set InformationVersion here, since $(Version) is already set at this point. -->
  <PropertyGroup>
    <InformationalVersion>$(Version). Commit Hash: $(GitHeadSha)</InformationalVersion>
  </PropertyGroup>
</Project>
