<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Microsoft.Orleans.CodeGenerator.MSBuild</PackageId>
    <Title>Microsoft Orleans Build-time Code Generator</Title>
    <Description>Microsoft Orleans build-time code generator to install in all grain interface &amp; implementation projects.</Description>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <BuildOutputTargetFolder>tasks</BuildOutputTargetFolder>
    <AssemblyName>Orleans.CodeGenerator.MSBuild</AssemblyName>
    <RootNamespace>Orleans.CodeGenerator.MSBuild</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <PublishRoot>bin\$(Configuration)\publish\</PublishRoot>
    <PublishDir>$(PublishRoot)$(TargetFramework)</PublishDir>
    <DevelopmentDependency>true</DevelopmentDependency>
  </PropertyGroup>

  <PropertyGroup>
    <PackAsTool>true</PackAsTool>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
  </PropertyGroup>
  
  <!-- Enable Global Invariant Mode to reduce package size -->
  <!-- see https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md -->
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="build\Microsoft.Orleans.CodeGenerator.MSBuild.targets" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="build\Microsoft.Orleans.CodeGenerator.MSBuild.targets">
      <Pack>true</Pack>
      <PackagePath>%(Identity)</PackagePath>
      <Visible>true</Visible>
    </Content>
    <Content Include="buildMultiTargeting\Microsoft.Orleans.CodeGenerator.MSBuild.targets">
      <Pack>true</Pack>
      <PackagePath>%(Identity)</PackagePath>
      <Visible>true</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime" Version="$(SystemRuntimeVersion)" />
    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
    <PackageReference Include="System.Runtime.Loader" Version="$(SystemRuntimeVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="$(MicrosoftExtensionsDependencyModelVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsLoggingVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="$(MicrosoftExtensionsLoggingVersion)" />
    <PackageReference Include="Microsoft.Build.Framework" Version="$(MicrosoftBuildVersion)" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="$(MicrosoftBuildVersion)" />
    <PackageReference Include="Microsoft.Build" Version="$(MicrosoftBuildVersion)" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="$(MicrosoftBuildVersion)" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="$(MicrosoftBuildVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="$(MicrosoftExtensionsDependencyModelVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsLoggingVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="$(MicrosoftExtensionsLoggingVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="$(MicrosoftExtensionsLoggingVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="$(MicrosoftCodeAnalysisVersion)" />
  </ItemGroup>
  
  <ItemGroup>
    <!-- This must come after all other PackageReference elements -->
    <PackageReference Update="@(PackageReference)" PrivateAssets="All" Publish="true" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Orleans.CodeGenerator\Orleans.CodeGenerator.csproj" PrivateAssets="all" Publish="true" />
  </ItemGroup>

  <!-- Start: PostBuildPublish -->
  <!-- In order to support incremental builds, only call the Publish target if inputs have changed. -->
  <PropertyGroup>
    <PublishCacheFileDir Condition="'$(IntermediateOutputPath)' != ''">$(IntermediateOutputPath)</PublishCacheFileDir>
    <PublishCacheFileDir Condition="'$(PublishCacheFileDir)' == ''">obj\$(Configuration)\$(TargetFramework)\</PublishCacheFileDir>
    <PublishCacheFile>$(PublishCacheFileDir)$(MSBuildProjectFile).Publish.cache</PublishCacheFile>
  </PropertyGroup>

  <ItemGroup>
    <PostBuildPublishInputs Include="@(Compile);@(ReferencePath)" />
    <PostBuildPublishInputs Remove="@(GeneratedAssemblyInfoFile)" />
  </ItemGroup>

  <Target
    Name="PostBuildPublish"
    AfterTargets="Build"
    DependsOnTargets="ResolveAssemblyReferences"
    Inputs="@(PostBuildPublishInputs)"
    Outputs="$(PublishCacheFile)"
    Condition="'$(TargetFramework)' != '' and '$(DesignTimeBuild)' == ''">
    
    <MSBuild Projects="$(MSBuildPRojectFullPath)" Properties="NoBuild=true" Targets="Publish" />

    <Hash ItemsToHash="@(PostBuildPublishInputs)">
      <Output TaskParameter="HashResult" PropertyName="Orleans_UpdatedInputPubCacheContents" />
    </Hash>

    <WriteLinesToFile Overwrite="true" File="$(PublishCacheFile)" Lines="$(Orleans_UpdatedInputPubCacheContents)" WriteOnlyWhenDifferent="True" />

    <ItemGroup>
      <FileWrites Include="$(PublishCacheFile)" />
    </ItemGroup>
  </Target>

</Project>