<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TestVersionGrains</RootNamespace>
    <AssemblyName>TestVersionGrains</AssemblyName>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)test\TestInfrastructure\Orleans.TestingHost.AppDomain\Orleans.TestingHost.AppDomain.csproj" />
    <ProjectReference Include="$(SourceRoot)test\TestInfrastructure\TestExtensions\TestExtensions.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Grains\TestGrainInterfaces\TestGrainInterfaces.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Grains\TestGrains\TestGrains.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Hagar" Version="0.2.2-dev-20190409095801" />
    <PackageReference Update="Hagar.CodeGenerator.MSBuild" Version="0.2.2-dev-20190409095801">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
