<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Microsoft.Orleans.Journaling.AzureStorage</PackageId>
    <Title>Microsoft Orleans Journaling provider for Azure Storage</Title>
    <Description>Azure Storage support for Microsoft Orleans Journaling.</Description>
    <PackageTags>$(PackageTags) Persistence State Machines</PackageTags>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <VersionSuffix Condition="$(VersionSuffix) != ''">$(VersionSuffix).alpha.1</VersionSuffix>
    <VersionSuffix Condition="$(VersionSuffix) == ''">alpha.1</VersionSuffix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Orleans.Journaling\Orleans.Journaling.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Orleans.Journaling.Tests" />
  </ItemGroup>

</Project>
