<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <Title>Microsoft Orleans gRPC Grain Source Generator</Title>
    <Description>C# Source Generator for Microsoft Orleans, generating code for gRPC interfaces.</Description>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IsOrleansFrameworkPart>false</IsOrleansFrameworkPart>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <Nullable>enable</Nullable>
    <WarnOnNullable>true</WarnOnNullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Templates\ClientProxy.liquid" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fluid.Core" PrivateAssets="all" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference Include="protobuf-net.Reflection" PrivateAssets="all" GeneratePathProperty="true" />
    <PackageReference Include="protobuf-net.Core" PrivateAssets="all" GeneratePathProperty="true" />

    <None Include="$(PkgFluid_Core)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="$(Pkgprotobuf-net_Reflection)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="$(Pkgprotobuf-net_Core)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Templates\ClientProxy.liquid" />
  </ItemGroup>

</Project>
