<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Microsoft.Orleans</PackageId>
    <Title>Microsoft Orleans Core Abstractions</Title>
    <Description>Legacy support library of Microsoft Orleans</Description>
    <TargetFrameworks>$(MultiTargetFrameworks)</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Orleans</RootNamespace>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orleans.Serialization\Orleans.Serialization.csproj" />
    <ProjectReference Include="..\Orleans.Core.Abstractions\Orleans.Core.Abstractions.csproj" />
    <ProjectReference Include="..\Orleans.Core\Orleans.Core.csproj" />
    <ProjectReference Include="..\Orleans.Runtime\Orleans.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BackwardCompatibility.Tests" />
  </ItemGroup>

</Project>
