<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <LangVersion>10</LangVersion>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Orleans.Core\Orleans.Core.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Legacy\Orleans.Legacy.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Runtime\Orleans.Runtime.csproj" />
    <ProjectReference Include="$(SourceRoot)test\TestInfrastructure\TestExtensions\TestExtensions.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Grains\TestGrains\TestGrains.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftTestSdkVersion)" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.115.5" />
    <PackageReference Include="xunit" Version="$(xUnitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(xUnitVersion)" />
  </ItemGroup>
</Project>