//
// WARNING: This file is autogenerated and any changes made to it may be overwritten.
// Generated on: 8/28/2024 1:15:18 PM
// Generated by: StateSourceCodeGenerator.exe
// Arguments: -i .\TesterInternal.dll -o ..\..\..\GrainDirectory\StateSpecifications.g.cs -n UnitTests.GrainDirectory 
//

namespace UnitTests.GrainDirectory
{
    using global::System;
    using global::System.Collections.Generic;
    using global::BraggerSpecs;

    public partial class RegistrationState : State
    {
        private string ActivationIdFieldName = "ActivationId";
        private string GrainIdFieldName = "GrainId";
        private string SiloAddressFieldName = "SiloAddress";

        protected DictionaryState<State> fieldStates;

        public RegistrationState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[ActivationIdFieldName] = new AtomicState<String>(default, null);
            fieldStates[GrainIdFieldName] = new AtomicState<String>(default, null);
            fieldStates[SiloAddressFieldName] = new AtomicState<String>(default, null);

            Initialize();
        }

        partial void Initialize();

        public String ActivationId
        {
            get => ((AtomicState<String>)fieldStates[ActivationIdFieldName]).Value;
            set => fieldStates[ActivationIdFieldName] = new AtomicState<String>(value);
        }

        public String GrainId
        {
            get => ((AtomicState<String>)fieldStates[GrainIdFieldName]).Value;
            set => fieldStates[GrainIdFieldName] = new AtomicState<String>(value);
        }

        public String SiloAddress
        {
            get => ((AtomicState<String>)fieldStates[SiloAddressFieldName]).Value;
            set => fieldStates[SiloAddressFieldName] = new AtomicState<String>(value);
        }

        protected override void CloneInternal(Dictionary<State, State> clonedMap)
        {
            var clonedObject = new RegistrationState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(RegistrationState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class ClientDirectoryState : State
    {
        private string DirectoryFieldName = "Directory";

        protected DictionaryState<State> fieldStates;

        public ClientDirectoryState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[DirectoryFieldName] = null;

            Initialize();
        }

        partial void Initialize();

        public DictionaryState<RegistrationState> Directory
        {
            get => (DictionaryState<RegistrationState>)fieldStates[DirectoryFieldName];
            set => fieldStates[DirectoryFieldName] = value;
        }

        protected override void CloneInternal(Dictionary<State, State> clonedMap)
        {
            var clonedObject = new ClientDirectoryState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(ClientDirectoryState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class SystemState : State
    {
        private string ClientsFieldName = "Clients";

        protected DictionaryState<State> fieldStates;

        public SystemState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[ClientsFieldName] = null;

            Initialize();
        }

        partial void Initialize();

        public DictionaryState<ClientDirectoryState> Clients
        {
            get => (DictionaryState<ClientDirectoryState>)fieldStates[ClientsFieldName];
            set => fieldStates[ClientsFieldName] = value;
        }

        protected override void CloneInternal(Dictionary<State, State> clonedMap)
        {
            var clonedObject = new SystemState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(SystemState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }
}
