<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BenchmarkGrainInterfaces</RootNamespace>
    <AssemblyName>BenchmarkGrainInterfaces</AssemblyName>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="Hagar" Version="0.2.2-dev-20190409095801" />
    <PackageReference Update="Hagar.CodeGenerator.MSBuild" Version="0.2.2-dev-20190409095801">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>