syntax = "proto3";

import "google/protobuf/descriptor.proto";
import "protos/grombo.proto";

package greet;

option csharp_namespace = "Foo.Bar";

extend google.protobuf.ServiceOptions {
  string grain_type = 50000;
}

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}

service NaySayer2 {
  rpc SayHello (grombo.SayNayRequest) returns (grombo.SayNayReply);
}
