<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\service.proto" GrpcServices="Client;Server" />
  </ItemGroup>

</Project>
