<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <PackageDescription>gRPC support for Microsoft Orleans</PackageDescription>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <IsOrleansFrameworkPart>false</IsOrleansFrameworkPart>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

</Project>