<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Orleans.DurableTasks\Orleans.DurableTasks.csproj" />
    <ProjectReference Include="..\..\src\Orleans.Server\Orleans.Server.csproj" />
  </ItemGroup>

</Project>
