<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPublishable>true</IsPublishable>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
    <ContainerRepository>chaos-fe</ContainerRepository>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DistributedChaos.ServiceDefaults\DistributedChaos.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
