<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Microsoft.Orleans.Legacy</PackageId>
    <Title>Microsoft Orleans legacy version support</Title>
    <Description>Legacy support library for Microsoft Orleans</Description>
    <TargetFrameworks>$(MultiTargetFrameworks)</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Orleans.Legacy</RootNamespace>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Orleans.Serialization\Orleans.Serialization.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Core.Abstractions\Orleans.Core.Abstractions.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Core\Orleans.Core.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Runtime\Orleans.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BackwardCompatibility.Tests" />
  </ItemGroup>

</Project>
